crew/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
    # re_path(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from . import views
from django.urls import path

app_name = 'music'

urlpatterns = [
    # /music/
    path('', views.IndexView.as_view(), name='index'),

    # register
    path('register/', views.UserFormView.as_view(), name='register'),

    # /music/id
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    # /music/album/add
    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),

    # /music/album/id
    path('album/<int:pk>', views.AlbumUpdate.as_view(), name='album-update'),

    # /music/album/id/delete
    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),


    # # ex: /polls/
    # path('', views.index, name='index'),
    # # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/results/
    # path('<int:question_id>/results/', views.results, name='results'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

companies/models.py
from django.db import models

# Create your models here.

music/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=255)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    song_title = models.CharField(max_length=255)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

companies/views.py
from django.shortcuts import render

# Create your views here.

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from music.models import Album, Song
from music.forms import UserForm


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    context_object_name = 'album'
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'genre', 'album_title', 'album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'genre', 'album_title', 'album_logo']


class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'

    # blank registration form - get method
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # proccess form data (form submit) - post method
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            # clean and normalized data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('music:index')
        return render(request, self.template_name, {'form': form})



# from django.shortcuts import render, get_object_or_404
# from django.http import HttpResponse
# from music.models import Album, Song
# from django.http import Http404
# from django.template import loader
#
#
# def index(request):
#     all_albums = Album.objects.all()
#     context = {
#         'all_albums': all_albums,
#     }
#     return render(request, 'music/index.html', context)
#
#
# def detail(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request, 'music/detail.html', {'album': album})
#

music/templates/music/album_form.html
{% extends 'music/base.html' %}


{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="col-md-8 order-md-1">
                <h4 class="mb-3">New Album</h4>
                <form class="needs-validation" action="" method="post" enctype="multipart/form-data" novalidate="">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}

                    <hr class="mb-4">

                    <button class="btn btn-primary btn-md" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</head>
<body>


<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">

    <a href="{% url 'music:index' %}" class="navbar-brand">
        <strong>Crew</strong>
    </a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarsExampleDefault" style="">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'music:index' %}">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-music-player" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M12 1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z"/>
                        <path fill-rule="evenodd"
                              d="M11 3H5v3h6V3zM5 2a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H5zm3 11a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                        <circle cx="8" cy="11" r="1"/>
                    </svg>
                    Album</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'music:index' %}">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-music" fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                              d="M4 1h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2zm0 1a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H4z"/>
                        <path d="M9 11.5c0 .828-.895 1.5-2 1.5s-2-.672-2-1.5.895-1.5 2-1.5 2 .672 2 1.5z"/>
                        <path fill-rule="evenodd" d="M9 5v6.5H8V5h1z"/>
                        <path d="M8 4.754a1 1 0 0 1 .725-.961l1.5-.429a1 1 0 0 1 1.275.962V6L8 7V4.754z"/>
                    </svg>
                    Song</a>
            </li>
            {#      <li class="nav-item">#}
            {#        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
            {#      </li>#}
            {#      <li class="nav-item dropdown">#}
            {#        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>#}
            {#        <div class="dropdown-menu" aria-labelledby="dropdown01">#}
            {#          <a class="dropdown-item" href="#">Action</a>#}
            {#          <a class="dropdown-item" href="#">Another action</a>#}
            {#          <a class="dropdown-item" href="#">Something else here</a>#}
            {#        </div>#}
            {#      </li>#}
        </ul>
        <ul class="navbar-nav navbar-right">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:album-add' %}">Add Album</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:index' %}">Logout</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" role="search" method="get" action="#">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" name="query" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>

    </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}




{% block title %}Album detail{% endblock %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% if error_message %}
                    <p><strong>{{ error_message }}</strong></p>
                {% endif %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img src="{{ album.album_logo.url }}" style="width: 100%">
                        <div class="card-body">
                            <h3 class="card-text">{{ album.album_title }}</h3>
                            <p class="card-text">{{ album.artist }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <p class="text-info">{{ album.genre }}</p>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-8">

                    <div class="btn-group">
                        <a href="{% url 'music:album-update' album.id %}">
                            <button type="button" class="btn btn-primary btn-md">Edit</button>
                        </a>
                        &nbsp;
                        <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}">
                            <button type="submit" class="btn btn-danger btn-md">Delete</button>
                        </form>
                    </div>
                    <hr class="mb-4">
                    <div class="card mb-8 shadow-sm">

                        <div class="card-body">
                            <h3 class="card-text">{{ album.artist }}</h3>
                            <hr class="mb-4">
                            <ul style="list-style: none;">
                                {% for song in album.song_set.all %}
                                    <li>
                                        <label for="song{{ forloop.counter }}">
                                            {{ song.song_title }} - {{ song.file_type }}
                                            {% if song.is_favorite %}
                                                *
                                            {% endif %}
                                        </label>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>


                </div>

            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/favorite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-md-2">{{ field.label_tag }}</label>
        <div class="col-md-10">{{ field }}</div>
    </div>

{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block title %}Album list{% endblock %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            {% if all_albums %}



                <h3>Here all my Albums</h3>
                <div class="row">
                    {% for album in all_albums %}
                        <div class="col-md-4">
                            <a href="{% url 'music:detail' album.id %}">
                                <div class="card mb-4 shadow-sm">

                                    <img src="{{ album.album_logo.url }}" style="width: 100%">

                                    <div class="card-body">
                                        <p class="card-text">{{ album.album_title }}</p>
                                        <div class="d-flex justify-content-between align-items-center">
                                            <small class="text-muted">20.07.20</small>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <h3>You don't have any albums</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/base.html' %}

{% block title %}Registration{% endblock %}
{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="col-md-8 order-md-1">
                <h4 class="mb-3">Create a new account</h4>
                <form class="needs-validation" action="" method="post" enctype="multipart/form-data" novalidate="">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}

                    <hr class="mb-4">

                    <button class="btn btn-primary btn-md" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}